scriptOnly = Yes

Interface  {
   Inputs {
   }
   Outputs {
   }
   Parameters { 
      Field strGroup     { type = string value = "UserDefined" persistent = false }
      Field color        { type = color value = "0.8 0.8 0.8" persistent = false }
      Field transparency { type = double value = 0      persistent = false }
      Field visible      { type = bool value = True    persistent = false }
   }
}