//----------------------------------------------------------------------------------
//! ML module LoadU3D definition
/*!
// \file    LoadU3D.script
// \author  Axel Newe
// \date    2015-10-16
*/
//----------------------------------------------------------------------------------

Description {
 
}


Interface {
  Parameters {
  }
}


Commands {
}


Window "Main Panel" {
  
  Category  {
    
    margin = 10
    
    Label { title = "Module is not yet implemented." }
    
  }
}

