//----------------------------------------------------------------------------------
//! ML module PDFCreateFibersFromLists definition
/*!
// \file    PDFCreateFibersFromLists.script
// \author  Axel Newe
// \date    2016-01-11
*/
//----------------------------------------------------------------------------------

Description {}

Commands {}  

Window { 
  
  Vertical {
  
    margin = 10
    expandY = Yes
    
    Label { title = "This module requires no settings." alignX = Center alignY = Center }
    
  }
  
}