//----------------------------------------------------------------------------------
//! Macro module UMDBoundingBoxWrapper2
/*!
// \file    UMDBoundingBoxWrapper2.script
// \author  Konrad Mühler
// \date    2004-12-21
//
// // 
*/
//----------------------------------------------------------------------------------


Interface {
  Inputs {
    Field inObjectContainer { internalName="UMDBoundingBox2.inObjectContainer"}
    Field inCurrentImage { internalName="BoundingBox.input0"}
  }
  Outputs {
  }
  Parameters {
  }
}
