



Window  {
   Category Parameters {
      Vertical  {
         expandY = NO
         Field = isUnique
      }
   }
}

//# MeVis signature v1
//# key: MFowDQYJKoZIhvcNAQEBBQADSQAwRgJBAKyWeOZdMOT9Sj40ZS32A8i8GAjHkcHh3QT05EJBoHkqE3S0/FOcZM6SFkMLVcjiDmzBdoc9REZUIl5061137BkCARE=:mbUARszcrJxTM2e3H2YskVHojl15mYg4OBjlYsSeJfjTYEVwkgvJJ0eFJB4r7/u64QtiMUxLsor5/MgAGO4iCA==
//# owner: MeVis Internal Developer
//# date: 2005-08-18T18:57:42
//# hash: gO6LstXgR/OHhV0I9e86TFhZvFgDu2U4ayk7DtlKgpIVv+buMknP6A/MuK1ZBndUNQ5XOjp87E1MIHSp6JAIOQ==
//# MeVis end
