//----------------------------------------------------------------------------------
//! Macro module METKClipping
/*!
// \file    METKClipping.script
// \author  Konrad
// \date    2006-01-24
//
// // 
*/
//----------------------------------------------------------------------------------

Interface  {
   Inputs {
      Field inObjectContainer { internalName = info.inObjectContainer }
   }
   Outputs {      
      Field outObjectContainer { internalName = info.outObjectContainer }
      Field clipBox { internalName = clipBoxOut.self }      
   }
   Parameters {      
   }
}

Commands  {
   // Add the local's parent path to the import path, so that Python looks for local packages
   importPath = "$(LOCAL)"
   
   // Include local functions
   source = "$(LOCAL)/METKClipping.py"
   
   // Call init() to initalize the script
   initCommand = init
   
   // Handle events from object container
   FieldListener info.outObjectContainer { callLater = false command = _cls_info.handleEvents }        
}

//# MeVis signature v1
//# key: MFowDQYJKoZIhvcNAQEBBQADSQAwRgJBAKyWeOZdMOT9Sj40ZS32A8i8GAjHkcHh3QT05EJBoHkqE3S0/FOcZM6SFkMLVcjiDmzBdoc9REZUIl5061137BkCARE=:mbUARszcrJxTM2e3H2YskVHojl15mYg4OBjlYsSeJfjTYEVwkgvJJ0eFJB4r7/u64QtiMUxLsor5/MgAGO4iCA==
//# owner: MeVis Internal Developer
//# date: 2005-08-18T17:40:57
//# hash: WQEHMsR7B0GvquHzDVEpPxacp3jqZyxcWbRLi7hbDagCk0x4neDwt7RHsJZf/1RlCEHC9vY+q+Z9gApI0CeNZw==
//# MeVis end

