#############################################################################
# Makefile for building: libMLOsiriXImporter_debug.dylib
# Generated by qmake (2.01a) (Qt 4.4.3) on: Tue Jul 7 15:18:25 2009
# Project:  MLOsiriXImporter.pro
# Template: lib
# Command: /Users/chuwa/Applications/MeVisLab.app/Contents/Support/MeVisLabProjectGenerator.app/Contents/Resources/qmake -spec /Users/chuwa/Applications/MeVisLab.app/Contents/Support/MeVisLabProjectGenerator.app/Contents/Resources/mkspecs/macx-xcode -macx CONFIG+=debug INITIAL_CONFIG=$$CONFIG -o MLOsiriXImporter_debug.xcodeproj/project.pbxproj MLOsiriXImporter.pro
#############################################################################

MOC       = /bin/moc
UIC       = /bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DMEVIS_TARGET=MLOsiriXImporter_debug -DBOOST_ALL_DYN_LINK -D_DEBUG -DDEBUG -DMeVisLab -DILAB5 -DMEVISLAB -DUNIX -DUNICODE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DMACOS -Dlinux -DLINUX -DLinux -DMLOSIRIXIMPORTER_EXPORTS
INCPATH       = -I/Users/chuwa/Applications/MeVisLab.app/Contents/Support/MeVisLabProjectGenerator.app/Contents/Resources/mkspecs/macx-xcode -I. -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/SharedIncludes -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/MLLinearAlgebra -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/MLUtilities -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/ML/include -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/MLLinearAlgebra -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/MLUtilities -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/Foundation/Sources/MLMemoryManager/Include -I/Users/chuwa/Applications/MeVisLab.app/Contents/Packages/MeVis/ThirdParty/Sources/misc/boost -I. -Itmp/debug/ui -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
compilers: $(OBJECTS_DIR)mlab_related_dummy_file
compiler_related_make_all: $(OBJECTS_DIR)mlab_related_dummy_file
compiler_related_clean:
	-$(DEL_FILE) $(OBJECTS_DIR)mlab_related_dummy_file
$(OBJECTS_DIR)mlab_related_dummy_file: ../../../Modules/ML/MLOsiriXImporter/MLOsiriXImporter.def 
	true

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_related_clean 

