//----------------------------------------------------------------------------------
//! Macro module UMDBoundingBoxWrapper2
/*!
// \file    UMDBoundingBoxWrapper2.script
// \author  Konrad Mühler
// \date    2004-12-21
//
// // 
*/
//----------------------------------------------------------------------------------


Interface {
  Inputs {
  	Field inObjectContainer { internalName="UMDBoundingBox2.inObjectContainer"}  	
  	Field inCurrentImage { internalName="BoundingBox.input0"}  	  	
  }
  Outputs {  	
  }
  Parameters {  	  	
  }
}


Commands {
  source = $(LOCAL)/UMDBoundingBoxWrapper2.js
}

//# MeVis signature v1
//# key: MFowDQYJKoZIhvcNAQEBBQADSQAwRgJBAKyWeOZdMOT9Sj40ZS32A8i8GAjHkcHh3QT05EJBoHkqE3S0/FOcZM6SFkMLVcjiDmzBdoc9REZUIl5061137BkCARE=:mbUARszcrJxTM2e3H2YskVHojl15mYg4OBjlYsSeJfjTYEVwkgvJJ0eFJB4r7/u64QtiMUxLsor5/MgAGO4iCA==
//# owner: MeVis Internal Developer
//# date: 2004-12-16T00:41:54
//# hash: GJYag+g+1AQmfKe4glDHONlpiS1dquBIV2PILoK7sQk8uVRRznH/hyflfQKwoa/6mmnLHo3JL4aHa9XWdnfCTA==
//# MeVis end

